import { chromium } from '@playwright/test'
const browser = await chromium.launch()
const ctx = await browser.newContext({ baseURL: 'http://localhost:4571' })
const A = await ctx.newPage()
const B = await ctx.newPage()
for (const [n, p] of [['A', A], ['B', B]]) p.on('pageerror', (e) => console.log(`[${n}] pageerror:`, String(e)))
const dump = async (label) => console.log(label, await A.evaluate(() => localStorage.getItem('gravity-works.save')))
await A.goto('/?level=kitchen01'); console.log(await A.locator('#gw-status').textContent())
await B.goto('/?level=kitchen02'); console.log(await B.locator('#gw-status').textContent())
const stale = await B.evaluate(() => window.__gwSave.loadSave())
console.log('stale:', JSON.stringify(stale))
await A.click('#gw-tray-gapLip'); await A.click('#gw-place')
await A.waitForFunction(() => JSON.parse(localStorage.getItem('gravity-works.save'))?.builds?.kitchen01, null, { timeout: 10000 })
await dump('after A place:')
stale.progress.stars.kitchen02 = 3
await B.evaluate((d) => window.__gwSave.saveSave(d), stale)
await dump('after B stale write:')
await A.waitForTimeout(1200)
await dump('after settle:')
await browser.close()
