/**
 * Stage 3 visual regression (PROMPT.md §10 Stage 3 accept line: "visual
 * baselines committed"; §5.8: canonical cameras, 1600x900 @ DPR 1).
 *
 * Four baselines, generated by THIS spec and committed under
 * `tests/visual/<platform>/<name>.png`:
 *
 *   establishing / hero / floor — the ratified canonical set
 *     (`?harness=1&scene=kitchen-set&shot=<shot>&post=on`, the three shots
 *     §5.8 defines, one deterministic frame behind `__sceneReady`);
 *   shell-kitchen01-idle — the shipped GAME shell
 *     (`/?level=kitchen01&post=on`, static-table framing, car parked at the
 *     start socket, nothing running; captured at the game canvas's own
 *     960x540, not the canonical 1600x900 — this baseline guards the page
 *     players see, the three above guard the ratified art).
 *
 * PLATFORM STRATEGY (the CI answer, stated so nobody is falsely green):
 * baselines live in **platform-suffixed directories** — tests/visual/darwin/
 * etc. The committed set was generated on macOS (Apple M5 Pro, headless
 * Chromium via SwiftShader); a Linux runner's SwiftShader/ANGLE can differ
 * by more than the antialiasing tolerance, so a missing directory is NEVER
 * a pass: the BASELINE test SKIPS loudly (skip message + console warning)
 * and shows as SKIPPED in the report, not green. To light a platform up,
 * run once with `GQA_UPDATE_BASELINES=1` on it — that regenerates and writes
 * the current platform's directory and skips the assertion — then commit
 * the PNGs. The platform-free cross-check that DOES run everywhere is the
 * exploration comparison: the harness output of the run is diffed against
 * the ratified docs/explorations/kitchen-set/ renders the Art Director
 * passed (Review 2026-10-07 round 2: 16/15/15, no zero).
 *
 * THE SPLIT (stage-3 review fix): baseline and exploration comparisons are
 * SEPARATE tests per shot. The exploration diff must never ride a code path
 * a missing platform baseline can abort — one test that `test.skip`s mid-
 * body would abort the exploration assertion too, making the CI on Linux
 * (no committed `tests/visual/linux/`) silently run NEITHER. So: one test
 * per shot asserts the committed baseline (skips per-platform), another
 * asserts the ratified render (NO skip in its body — it runs on every
 * platform). Prove the split by simulating a baseline-less platform:
 * `GQA_BASELINE_DIR=tests/visual/linux npx playwright test visual` — the
 * baseline tests report SKIPPED, the exploration tests still RUN and pass.
 *
 * Comparison: pixelmatch at threshold 0.1 with antialiasing allowance;
 * gate is <= 0.1 % differing pixels (4,320 of 1,440,000 at 1600x900) —
 * small but nonzero, so a stable renderer passes and a real change fails.
 *
 * FINDING CHECK: each canonical shot is additionally diffed against the
 * ratified exploration PNG; > 2 % mismatch is a finding and fails with the
 * number printed.
 *
 * Rebaselining deliberately: `GQA_UPDATE_BASELINES=1 E2E_PORT=<port> npx
 * playwright test visual`.
 */
import { test, expect } from '@playwright/test'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import pixelmatch from 'pixelmatch'
import { PNG } from 'pngjs'

interface HarnessWindow {
  __sceneReady?: boolean
  __sceneError?: string
}

/** Same capture convention as tools/render.mjs: canvas element screenshot. */
const captureCanvas = async (page: import('@playwright/test').Page): Promise<Buffer> =>
  (await page.locator('canvas').screenshot()) as Buffer

const decode = (buf: Buffer): PNG => PNG.sync.read(buf)

/** pixelmatch differing-pixel ratio between two same-size decoded PNGs. */
const diffRatio = (a: PNG, b: PNG): { ratio: number; count: number } => {
  if (a.width !== b.width || a.height !== b.height) {
    throw new Error(`size mismatch ${a.width}x${a.height} vs ${b.width}x${b.height} — the renderer changed resolution; that is a finding, not noise`)
  }
  const count = pixelmatch(a.data, b.data, undefined, a.width, a.height, {
    threshold: 0.1, // per-pixel color distance: the antialiasing allowance
    includeAA: false,
  })
  return { ratio: count / (a.width * a.height), count }
}

/** Gate: <= 0.1 % differing pixels (nonzero: antialiasing is allowed). */
const MAX_DIFF_RATIO = 0.001
/** Harness-vs-exploration finding threshold: > 2 % is a reported finding. */
const EXPLORATION_MAX_RATIO = 0.02

const PLATFORM = process.platform // 'darwin' | 'linux' | 'win32'
// Env override simulates a platform with no committed baseline (the CI-truth
// probe for the split above); unset, this is the platform directory itself.
const BASELINE_DIR = process.env.GQA_BASELINE_DIR ?? join('tests', 'visual', PLATFORM)
const REBASE = process.env.GQA_UPDATE_BASELINES === '1'

/**
 * Compare a fresh capture with the committed baseline for THIS platform.
 * Missing baseline: loud skip — never a silent pass — unless rebasing.
 */
const againstBaseline = (shotName: string, pngBuf: Buffer): void => {
  const path = join(BASELINE_DIR, `${shotName}.png`)
  if (REBASE) {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, pngBuf)
    console.log(`[visual] REBASELINED ${path} (assertion skipped for this run)`)
    return
  }
  test.skip(
    !existsSync(path),
    `SKIPPED: no committed baseline for platform "${PLATFORM}" (${path}). This is NOT a pass — ` +
      `generate one on this platform with GQA_UPDATE_BASELINES=1 and commit it.`,
  )
  const base = decode(readFileSync(path))
  const shot = decode(pngBuf)
  const { ratio, count } = diffRatio(shot, base)
  console.log(
    `[visual] ${shotName}: ${(ratio * 100).toFixed(4)} % differing pixels (${count} of ${shot.width * shot.height}) vs ${path}`,
  )
  expect(
    ratio,
    `${shotName}: ${(ratio * 100).toFixed(3)} % of pixels differ from the committed baseline (> ${(MAX_DIFF_RATIO * 100).toFixed(1)} %)`,
  ).toBeLessThanOrEqual(MAX_DIFF_RATIO)
}

/** Compare a canonical capture with the ratified exploration render. */
const againstExploration = (shotName: string, pngBuf: Buffer): void => {
  const path = join('docs', 'explorations', 'kitchen-set', `${shotName}.png`)
  const base = decode(readFileSync(path))
  const shot = decode(pngBuf)
  const { ratio, count } = diffRatio(shot, base)
  console.log(
    `[visual vs ratified] ${shotName}: ${(ratio * 100).toFixed(4)} % differing pixels (${count}) vs ${path}`,
  )
  expect(
    ratio,
    `FINDING: harness output differs from the ratified exploration render by ${(ratio * 100).toFixed(2)} % (> 2 %): ${path}`,
  ).toBeLessThanOrEqual(EXPLORATION_MAX_RATIO)
}

test.use({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 1 })

/** One deterministic canonical frame behind __sceneReady. */
const captureCanonical = async (
  page: import('@playwright/test').Page,
  shot: 'establishing' | 'hero' | 'floor',
): Promise<Buffer> => {
    await page.goto(`/?harness=1&scene=kitchen-set&shot=${shot}&post=on`)
    await page.waitForFunction(
      () => {
        const w = window as unknown as HarnessWindow
        return w.__sceneReady === true || w.__sceneError !== undefined
      },
      undefined,
      { timeout: 60_000 },
    )
    const err = await page.evaluate(() => (window as unknown as HarnessWindow).__sceneError)
    expect(err, `harness scene error: ${err}`).toBeUndefined()
    return captureCanvas(page)
}

for (const shot of ['establishing', 'hero', 'floor'] as const) {
  // Baseline comparison: platform-scoped, LOUD skip where no directory is
  // committed. Nothing else may live in this body — a test.skip here aborts
  // only this test.
  test(`canonical kitchen-set ${shot} matches its committed baseline`, async ({ page }) => {
    againstBaseline(shot, await captureCanonical(page, shot))
  })

  // Exploration comparison: platform-independent ratified-render diff. NO
  // skip path anywhere in this body — it runs (and can fail) on every
  // platform, including a Linux CI with no committed baselines.
  test(`canonical kitchen-set ${shot} matches the ratified exploration render`, async ({ page }) => {
    againstExploration(shot, await captureCanonical(page, shot))
  })
}

test('game shell kitchen01 idle matches its committed baseline', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (err) => errors.push(String(err)))
  await page.goto('/?level=kitchen01&post=on')
  await expect(page.locator('#gw-status')).toContainText('ready', { timeout: 60_000 })
  // Settle two rAF frames after "ready". Nothing animates on the idle
  // table (no run is active, the liquid uTime stays 0), so any settled
  // frame is THE frame.
  await page.evaluate(
    () =>
      new Promise<void>((resolve) =>
        requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
      ),
  )
  const canvas = page.locator('#gw-canvas')
  // The shell renders at the GAME resolution — stated for the record.
  expect(
    await canvas.evaluate((c) => `${(c as HTMLCanvasElement).width}x${(c as HTMLCanvasElement).height}`),
  ).toBe('960x540')
  const buf = (await canvas.screenshot()) as Buffer
  againstBaseline('shell-kitchen01-idle', buf)
  expect(errors).toEqual([])
})
