/**
 * The `Level` shape the world, builder and replay all read. Deliberately
 * minimal (docs/vault/Concepts/Track Kit.md): a start socket, a budget, a par,
 * a seed and whatever a placeholder build looks like until the Feel Engineer's
 * real track plugs in. Everything here is plain data — a level is serialisable
 * and a replay needs nothing more than (level, build, seed).
 */
import type { Socket } from '../track/socket.ts';
import type { Build } from '../track/build.ts';

export interface LevelPar {
  /** Reference piece count for the 2-star line. */
  pieces: number;
  /** Reference finish time in seconds for the 3-star line. */
  time: number;
}

export interface Level {
  id: string;
  name: string;
  /** Run seed. Folded into the state hash so (level, build, seed) is complete. */
  seed: number;
  /** Where the car spawns and where the builder's first open socket lives. */
  startSocket: Socket;
  /** Total pieces the player may place (sandbox levels use a big number). */
  budget: number;
  par: LevelPar;
  /** Hard run cap in seconds; beyond it the run ends as `timeout`. */
  maxTime: number;
  /**
   * The level's reference build as plain data. For `feeltrack` this is now
   * the REAL kit feel track (laid from `src/feel/feeltrack.ts`'s constants);
   * the seam is unchanged — same signature, nothing else changes.
   */
  placeholderBuild(): Build;
  /**
   * THE BLOCKED-RIM ASK (P4 shortlist item 1, the kitchen02 truth): when
   * true, a seat that overlaps the GOAL object's own body is refused — the
   * ghost goes red and names the goal ("blocked — the cup is in the way"),
   * and the Place button will not seat there. On a CHOICE rung whose tray is
   * the union of two lines, the whole-tray dump's tail piece always lands at
   * the goal's rim (reach-sum invariance: union = par + one piece, always
   * PAST the cup), so the guard is what makes "place everything" an
   * un-buildable line — the union dump must CHOOSE, and can die choosing.
   * Placement-layer only: it adds no geometry, no collider and no physics
   * read, so every par replay hash is byte-identical with the flag set
   * (proved in `tests/unit/goal-guard.test.ts` + `replay:all`).
   */
  blockedGoalSeat?: boolean;
  /**
   * The level's REFERENCE build for pars (brief §9.2: "a level's par is set
   * by the Level Designer's reference build and regenerated by script").
   * `scripts/gen-pars.mjs` replays THIS build headless and writes the
   * measured time and piece count into `src/world/pars.json`. Optional until
   * a level ships one: the pars script falls back to `placeholderBuild`, so
   * the feel track's real-kit chain is its own reference until the Level
   * Designer authors a better one.
   */
  parBuild?(): Build;
}
