/**
 * Star scoring (brief §1: "Every level has three stars: finish at all; finish
 * under the par piece count; finish under the par time") and the pars layer.
 *
 * Everything here is pure data over a plain result object — no World import,
 * no DOM — so the level ladder is testable in Node and the result panel is
 * just one consumer. The result shape is wider than `RunStatus` on purpose:
 * `hazard` is a stage-3 outcome (the kitchen tap, the drain, ...) that
 * `src/world/world.ts` will report once hazards exist; results with
 * `hazardsTouched > 0` still score by the same three lines (hazards are
 * avoided, not survived-for-points — the brief's stars say finish/pieces/
 * time and nothing else).
 *
 * Pars come from `pars.json`, REGENERATED by `scripts/gen-pars.mjs`
 * (`npm run pars`, CI-gated with `npm run pars -- --check`, brief §9.2).
 * The per-level `Level.par` field stays as a fallback for levels the script
 * has not seen yet, and `parFor` says which one answered.
 */
import parsFile from './pars.json';

/** Terminal run outcomes: `World`'s statuses plus the stage-3 `hazard`. */
export type RunOutcome = 'finished' | 'fell' | 'stalled' | 'hazard' | 'timeout';

/** The plain result the scorer reads — everything the star lines depend on. */
export interface RunResult {
  status: RunOutcome;
  /** Run time in seconds. */
  time: number;
  /** Pieces placed in the build that ran. */
  piecesUsed: number;
  /** Distinct hazard effects that touched the car (0 until hazards ship). */
  hazardsTouched: number;
}

export interface Par {
  /** Reference piece count: the 2-star line. */
  pieces: number;
  /** Reference time in seconds: the 3-star line. */
  time: number;
}

export type StarCount = 0 | 1 | 2 | 3;

/**
 * The three lines, exactly as brief §1 states them — each line is one star,
 * independently: finish at all, `piecesUsed <= par.pieces`, `time <=
 * par.time`. The comparisons are `<=` against the SCRIPT-recomputed par
 * (finish at the par time is the reference build's own pace — matching it is
 * good enough; recorded in the Decision Log).
 */
export function starsFor(result: RunResult, par: Par): StarCount {
  if (result.status !== 'finished') return 0;
  let stars = 1;
  if (result.piecesUsed <= par.pieces) stars += 1;
  if (result.time <= par.time) stars += 1;
  return stars as StarCount;
}

/** The ★/☆ readout the result panel and the share card both render. */
export function starGlyphs(stars: StarCount): string {
  return '★'.repeat(stars) + '☆'.repeat(3 - stars);
}

// ---- pars.json (generated — do not hand-edit) -------------------------------

interface ParsEntry {
  levelId: string;
  parPieces: number;
  parTime: number;
}

function parsShape(value: unknown): value is ParsEntry[] {
  return (
    Array.isArray(value) &&
    value.every(
      (e) =>
        typeof e === 'object' &&
        e !== null &&
        typeof (e as ParsEntry).levelId === 'string' &&
        Number.isFinite((e as ParsEntry).parPieces) &&
        Number.isFinite((e as ParsEntry).parTime),
    )
  );
}

/** Parsed `src/world/pars.json`. Garbage degrades to "{}" (fallback pars),
 * never a crash — a broken generated file must not brick the game. */
export const PARS: Record<string, Par> = {};
if (parsShape(parsFile)) {
  for (const entry of parsFile as ParsEntry[]) {
    PARS[entry.levelId] = { pieces: entry.parPieces, time: entry.parTime };
  }
}

/**
 * The par a run is scored against: the regenerated line when the script has
 * recorded one for this level, else the level's own `par` field.
 */
export function parFor(levelId: string, fallback: Par): Par {
  return PARS[levelId] ?? fallback;
}
