#!/usr/bin/env node
/**
 * Pars regeneration (brief §9.2: "a level's par is set by the Level Designer's
 * reference build and regenerated by script"; stage-4 accept line: "pars
 * regenerated by script").
 *
 * For every registered level with a reference build — the optional
 * `Level.parBuild`, falling back to `placeholderBuild` (the feel track's
 * real-kit chain is its own reference until a better one is authored) — this
 * replays the build headless through `src/replay/replay.ts` and records:
 *
 *   { levelId, parTime, parPieces }
 *
 * `parPieces` is the TRAY-basis count — the number of pieces the reference
 *  build asks the PLAYER to place, i.e. the reference build's pieces minus
 *  the level's built-in `fixtures` (the book-stack ramp, the counter cup, the
 *  bowl rim, the L02 run-out). That is the basis every consumer compares it
 *  on: the builder counts tray placements only (`Builder.playerCount`), and a
 *  level's tray total IS its `budget` (`kitchenLevel`), so a piece-count par
 *  on any other basis is a star line no run can ever miss — the deployed
 *  panel said "3 pieces — par 5" on a three-piece tutorial. Levels with no
 *  fixture table (the feel rig, which ships no tray) keep the whole-build
 *  count, which is what that level's counter already reported.
 *
 * `parTime` is the measured finish time rounded UP to the next 0.05 s, so the
 * 3-star line is "at least as fast as the reference build" without punishing
 * float jitter at the exact reference time. A par build that does not finish
 * is an error, not a par — the script exits 2 rather than ship a par nobody
 * can reach.
 *
 * `npm run pars` writes `src/world/pars.json` (the file `src/world/stars.ts`
 * imports). `npm run pars -- --check` recomputes and FAILS (exit 1, CI gate)
 * if the shipped file drifts from the recomputation — a level whose reference
 * build got retuned without regenerating pars breaks CI loudly.
 *
 * Cross-platform honesty: replay times are only guaranteed identical on the
 * same physics build (see docs/vault/Concepts/Determinism.md); the 0.05 s
 * ceil absorbs sub-tick jitter, and the check is run in CI on the same
 * runner image the determinism tests already depend on.
 *
 * Requires Node >= 22.18 (native TypeScript type stripping — the level files
 * and `src/replay` are imported directly, no build step).
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const OUT = new URL('../src/world/pars.json', import.meta.url);
// Level modules register themselves on import. Adding a level file means
// adding its import here (same one-liner convention as the share registry
// tests) — nothing else in this script enumerates levels by hand.
await import('../src/world/levels/feeltrack.level.ts');
await import('../src/world/levels/kitchen01.level.ts');
await import('../src/world/levels/kitchen02.level.ts');
await import('../src/world/levels/kitchen03.level.ts');
await import('../src/world/levels/kitchen04.level.ts');
await import('../src/world/levels/kitchen05.level.ts');
await import('../src/world/levels/bedroom01.level.ts');
await import('../src/world/levels/bedroom02.level.ts');
await import('../src/world/levels/bedroom03.level.ts');
await import('../src/world/levels/bedroom04.level.ts');
await import('../src/world/levels/bathroom01.level.ts');
await import('../src/world/levels/bathroom02.level.ts');
await import('../src/world/levels/bathroom03.level.ts');
await import('../src/world/levels/bathroom04.level.ts');
const { LEVELS } = await import('../src/world/levels/feeltrack.level.ts');
const { replayRun } = await import('../src/replay/replay.ts');

/** Measured seconds -> the shipped par line (ceil to 0.05 s). */
function parTimeOf(seconds) {
  return Math.ceil(seconds * 20 - 1e-9) / 20;
}

async function computePars() {
  const entries = [];
  for (const level of Object.values(LEVELS)) {
    const build = level.parBuild ? level.parBuild() : level.placeholderBuild();
    const run = await replayRun(level, build);
    if (run.status !== 'finished') {
      console.error(
        `gen-pars: ${level.id} reference build ended "${run.status}" at ${run.time.toFixed(2)} s — a par must be finishable`,
      );
      process.exit(2);
    }
    // tray basis: everything the reference build places that is NOT a
    // built-in fixture (levels without a fixture table count everything,
    // which is what their counter already reports)
    const fixtures = level.fixtures ?? {};
    const trayPieces = build.pieces.filter((p) => !(p.def in fixtures)).length;
    entries.push({
      levelId: level.id,
      parPieces: trayPieces,
      parTime: parTimeOf(run.time),
    });
  }
  entries.sort((a, b) => (a.levelId < b.levelId ? -1 : a.levelId > b.levelId ? 1 : 0));
  const stable = entries.map((e) => ({ levelId: e.levelId, parPieces: e.parPieces, parTime: e.parTime }));
  return `${JSON.stringify(stable, null, 2)}\n`;
}

const text = await computePars();

if (process.argv.includes('--check')) {
  let shipped = null;
  try {
    shipped = await readFile(fileURLToPath(OUT), 'utf8');
  } catch {
    console.error('gen-pars --check: src/world/pars.json does not exist; run `npm run pars`');
    process.exit(1);
  }
  if (shipped !== text) {
    console.error('gen-pars --check: shipped pars.json drifts from the recomputed pars.');
    console.error(`--- shipped ---\n${shipped}--- recomputed ---\n${text}`);
    process.exit(1);
  }
  console.log('gen-pars --check: pars.json matches the recomputed pars');
} else {
  await writeFile(fileURLToPath(OUT), text);
  console.log(`gen-pars: wrote ${fileURLToPath(OUT)} (${JSON.parse(text).length} levels)`);
}
