/**
 * The stars layer and the physics-note evidence system (brief §9.1 + §9.2).
 * The note tests build RunEvidence objects directly — each case is one row
 * of the coverage map in `src/ui/result.ts` / `Modules/ui.md` — plus one
 * test that the recorder DERIVES the witnesses honestly from a sample
 * stream.
 */
import { describe, expect, test } from 'vitest';
import { PARS, parFor, starGlyphs, starsFor, type RunResult } from '../../src/world/stars.ts';
import {
  createRunRecorder,
  emptyEvidence,
  physicsNote,
  pitchOfQuat,
  resultModel,
  type RunEvidence,
  type RunSample,
} from '../../src/ui/result.ts';
import { FEEL_TRACK_KINDS } from '../../src/feel/feeltrack.ts';
import { FEELTRACK } from '../../src/world/levels/feeltrack.level.ts';

const PAR = { pieces: 8, time: 4 };

function finished(over: Partial<RunResult> = {}): RunResult {
  return { status: 'finished', time: 3, piecesUsed: 7, hazardsTouched: 0, ...over };
}

describe('starsFor', () => {
  test('only a finish earns any star', () => {
    for (const status of ['fell', 'stalled', 'hazard', 'timeout'] as const) {
      expect(starsFor({ status, time: 1, piecesUsed: 1, hazardsTouched: 0 }, PAR)).toBe(0);
    }
  });

  test('finishing above both par lines is one star', () => {
    expect(starsFor(finished({ piecesUsed: 9, time: 5 }), PAR)).toBe(1);
  });

  test('the piece line is <= par pieces', () => {
    expect(starsFor(finished({ piecesUsed: 8, time: 5 }), PAR)).toBe(2); // exactly par counts
    expect(starsFor(finished({ piecesUsed: 4, time: 5 }), PAR)).toBe(2);
  });

  test('the time line is <= par time and counts independently of pieces', () => {
    expect(starsFor(finished({ piecesUsed: 9, time: 4 }), PAR)).toBe(2); // fast but chunky
    expect(starsFor(finished({ piecesUsed: 8, time: 4 }), PAR)).toBe(3); // exactly par time counts
    expect(starsFor(finished(), PAR)).toBe(3);
  });

  test('hazardsTouched does not move the lines (finish/pieces/time, nothing else)', () => {
    expect(starsFor(finished({ hazardsTouched: 2 }), PAR)).toBe(3);
  });

  test('starGlyphs pads to three', () => {
    expect(starGlyphs(0)).toBe('☆☆☆');
    expect(starGlyphs(3)).toBe('★★★');
  });
});

describe('pars.json (generated by scripts/gen-pars.mjs)', () => {
  test('the feel track par is the reference build measured, not hand-mirrored', () => {
    expect(PARS[FEELTRACK.id]).toBeDefined();
    expect(PARS[FEELTRACK.id]!.pieces).toBe(FEEL_TRACK_KINDS.length);
    // measured 3.008 s on the par build; the line is the 0.05 s ceil above it
    expect(PARS[FEELTRACK.id]!.time).toBeGreaterThanOrEqual(3.0);
    expect(PARS[FEELTRACK.id]!.time).toBeLessThanOrEqual(3.5);
  });

  test('parFor prefers the regenerated line and falls back per level', () => {
    const fallback = { pieces: 99, time: 99 };
    expect(parFor(FEELTRACK.id, fallback)).toEqual(PARS[FEELTRACK.id]);
    expect(parFor('no-such-level', fallback)).toEqual(fallback);
  });
});

// ---- the note ---------------------------------------------------------------

function ev(over: Partial<RunEvidence> = {}): RunEvidence {
  return { ...emptyEvidence(0), ...over };
}

const run = (status: RunResult['status'], over: Partial<RunResult> = {}): RunResult => ({
  status,
  time: 3,
  piecesUsed: 5,
  hazardsTouched: 0,
  ...over,
});

describe('physicsNote (coverage map of src/ui/result.ts)', () => {
  test('a finished run gets no note', () => {
    expect(physicsNote(finished(), ev())).toBe('');
  });

  test('any failure with a hazard touched names the hazard line first', () => {
    for (const status of ['fell', 'stalled', 'hazard', 'timeout'] as const) {
      expect(physicsNote(run(status, { hazardsTouched: 1 }), ev())).toMatch(/hazard/);
    }
  });

  test('fell after a nose-down touchdown -> fell off nose-first', () => {
    expect(physicsNote(run('fell'), ev({ lastTouchdownPitch: -0.6 }))).toMatch(/^fell off nose.first/);
  });

  test('fell or stalled slow at a real apex -> too slow at the top of the loop', () => {
    // climb 0.20 m -> ring radius ~0.10 -> floor sqrt(9.81 * 0.10) ~= 0.99 m/s
    const slowApex = ev({ apexY: 0.2, apexSpeed: 0.4 });
    expect(physicsNote(run('fell'), slowApex)).toMatch(/top of the loop/);
    expect(physicsNote(run('stalled'), slowApex)).toMatch(/top of the loop/);
    // a fast apex on the same climb must NOT claim this
    expect(physicsNote(run('stalled'), ev({ apexY: 0.2, apexSpeed: 2.0, lastPushTime: 1 }))).not.toMatch(
      /top of the loop/,
    );
  });

  test('fell after a long flight -> the jump outran the landing', () => {
    // the long-jump line needs BOTH witnesses: a long flight AND a deck
    // that launched it upward (stage-4 note matrix, playtest K)
    expect(
      physicsNote(run('fell'), ev({ finalAirtime: 0.8, finalTakeoffVy: 1.2 })),
    ).toMatch(/^fell off .*jump/);
  });

  test('fell airborne-but-not-launched -> no "long jump" lie (playtest K)', () => {
    // every fall off a counter is airborne ~0.4 s; a drive-off (no rise)
    // must get the honest line, not the launched-jump one
    expect(
      physicsNote(run('fell'), ev({ finalAirtime: 0.433, finalTakeoffVy: -0.13 })),
    ).toMatch(/^fell off the set/);
  });

  test('fell otherwise -> fell off the set', () => {
    expect(physicsNote(run('fell'), ev())).toMatch(/fell off the set/);
  });

  test('stalled nose-high -> stalled going uphill', () => {
    expect(physicsNote(run('stalled'), ev({ lastGroundedPitch: 0.3 }))).toMatch(/^stalled .*uphill/);
  });

  test('stalled on the level after a recorded push -> last-push line', () => {
    expect(physicsNote(run('stalled'), ev({ lastPushTime: 2.1 }))).toMatch(/last push/);
  });

  test('stalled with no witnesses at all -> the friction line', () => {
    expect(physicsNote(run('stalled'), ev())).toMatch(/friction/);
  });

  test('timeout -> the time-limit line', () => {
    expect(physicsNote(run('timeout'), ev())).toMatch(/^timed out/);
  });

  test('an outcome the evidence cannot explain gets the catch-all, never a guess', () => {
    const impossible = run('finished' as RunResult['status']);
    expect(physicsNote({ ...impossible, status: 'unknown' as RunResult['status'] }, ev())).toBeTruthy();
  });

  test('every failure status produces a non-empty one-liner', () => {
    for (const status of ['fell', 'stalled', 'hazard', 'timeout'] as const) {
      const note = physicsNote(run(status), ev());
      expect(note.length).toBeGreaterThan(0);
      expect(note).not.toContain('\n');
    }
  });

  test('stage 3 vocabulary: the note head verb EQUALS the shell status-line verb', () => {
    // one verb per physics event (playtest E "snapped vs seated"; G "says
    // seated with a flew-off verdict") — the word the status line leads
    // with (boot.ts runStatusLine) is the word the note leads with; no
    // second verb for the same end (no "flew off" for a fell, no "ran
    // out" for a stall). The placement ghost's amber word is `reversed`
    // (builder.ts), never the physics word for sitting in the cup.
    expect(physicsNote(run('fell'), ev())).toMatch(/^fell off/);
    expect(physicsNote(run('stalled'), ev())).toMatch(/^stalled/);
    expect(physicsNote(run('timeout'), ev())).toMatch(/^timed out/);
    const all: RunResult['status'][] = ['fell', 'stalled', 'timeout'];
    for (const s of all) {
      const note = physicsNote(run(s), ev());
      expect(note).not.toMatch(/\bflew off\b|\bran out\b|\bseated\b|\blanded\b/);
    }
  });
});

// ---- the recorder -----------------------------------------------------------

function sample(over: Partial<RunSample['car']> & { time?: number } = {}): RunSample {
  return {
    time: over.time ?? 0,
    car: {
      pos: { x: 0, y: 0, z: 0 },
      quat: { w: 1, x: 0, y: 0, z: 0 },
      speed: 0.5,
      grounded: true,
      ...over,
    },
  };
}

function noseQuat(pitch: number): { w: number; x: number; y: number; z: number } {
  // rotation of +pitch about +z carries (1,0,0) up: +=nose-up
  const h = pitch / 2;
  return { w: Math.cos(h), x: 0, y: 0, z: Math.sin(h) };
}

describe('run recorder', () => {
  test('pitchOfQuat reads chassis nose-up angle', () => {
    expect(pitchOfQuat({ w: 1, x: 0, y: 0, z: 0 })).toBeCloseTo(0, 6);
    expect(pitchOfQuat(noseQuat(0.3))).toBeCloseTo(0.3, 6);
    expect(pitchOfQuat(noseQuat(-0.5))).toBeCloseTo(-0.5, 6);
  });

  test('witnesses derive from the sample stream', () => {
    const rec = createRunRecorder();
    rec.reset(sample({ time: 0 }));
    rec.sample(sample({ time: 1 / 120, pos: { x: 0, y: 0.2, z: 0 }, speed: 0.4 })); // apex
    rec.sample(sample({ time: 0.1, grounded: false, quat: noseQuat(-0.6) })); // airborne, nose down
    rec.sample(sample({ time: 0.2, grounded: true, quat: noseQuat(-0.6) })); // touchdown nose-first
    rec.sample(sample({ time: 0.3, speed: 0.9 })); // a gain -> last push
    rec.sample(sample({ time: 0.4, speed: 0.9, grounded: true, quat: noseQuat(0.1) }));
    const e = rec.evidence();
    expect(e.startY).toBe(0);
    expect(e.apexY).toBe(0.2);
    expect(e.apexSpeed).toBe(0.4);
    expect(e.lastTouchdownPitch).toBeCloseTo(-0.6, 5);
    expect(e.lastPushTime).toBe(0.3);
    expect(e.finalAirtime).toBeCloseTo(0, 6); // the flight ended before the end
  });
});

describe('resultModel', () => {
  test('pairs stars and the note with the run numbers', () => {
    const m = resultModel(run('stalled'), PAR, ev());
    expect(m.stars).toBe(0);
    expect(m.note).toMatch(/friction|loop|uphill|push/);
    const f = resultModel(finished({ time: 2, piecesUsed: 5 }), PAR, ev());
    expect(f.stars).toBe(3);
    expect(f.note).toBe('');
  });
});
